// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertFile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConvertFile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetInitialFiles() {
  return window['go']['main']['App']['GetInitialFiles']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
