// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertFile(arg1:string,arg2:string,arg3:number,arg4:boolean,arg5:string,arg6:string):Promise<void>;

export function GetFileInfo(arg1:string):Promise<main.FileInfo>;

export function GetInitialFiles():Promise<Array<main.FileInfo>>;

export function SelectFiles():Promise<Array<main.FileInfo>>;

export function SelectFolder():Promise<string>;
